import { 
  Profile, Skill, ProfileSkill, Project, Company, Job, 
  Application, Assessment, AssessmentAttempt, NotificationItem 
} from '../types';

export const SKILL_UUIDS = {
  REACT: 'f2ee449f-093d-4ec9-b61e-0455ab2e9fe2',
  JAVASCRIPT: '6cea9325-b180-4551-ae7c-a4d0a20f1f2c',
  TYPESCRIPT: '55a5d36c-1b07-4097-a5ec-58bf787a0d18',
  PYTHON: '93f4502a-7ce9-46d4-9c34-5f9a048d4c7a',
  NODEJS: 'bf532902-8f8e-46a0-9ad0-5dd119feab5a',
  SQL: '8d9ff127-1b73-454d-9b3a-3b2ca42b5cd8',
  DSA: '785e7ccb-c57f-4c54-ab2d-c55b51cfd1c1',
  DOCKER: '73192fc4-3f76-4959-bd23-d51787a4c277',
  GIT: '7381485a-10a5-4847-a1fd-ac6ceab78196',
  ML: '930fe491-5a7a-4271-bea6-f436bee0bf5a',
};

export const SKILL_ALIAS_MAP: Record<string, string> = {
  'sk_react': SKILL_UUIDS.REACT,
  'react': SKILL_UUIDS.REACT,
  'sk_js': SKILL_UUIDS.JAVASCRIPT,
  'javascript': SKILL_UUIDS.JAVASCRIPT,
  'js': SKILL_UUIDS.JAVASCRIPT,
  'sk_ts': SKILL_UUIDS.TYPESCRIPT,
  'typescript': SKILL_UUIDS.TYPESCRIPT,
  'ts': SKILL_UUIDS.TYPESCRIPT,
  'sk_py': SKILL_UUIDS.PYTHON,
  'python': SKILL_UUIDS.PYTHON,
  'py': SKILL_UUIDS.PYTHON,
  'sk_node': SKILL_UUIDS.NODEJS,
  'node.js': SKILL_UUIDS.NODEJS,
  'nodejs': SKILL_UUIDS.NODEJS,
  'node': SKILL_UUIDS.NODEJS,
  'sk_sql': SKILL_UUIDS.SQL,
  'sql': SKILL_UUIDS.SQL,
  'sk_dsa': SKILL_UUIDS.DSA,
  'dsa': SKILL_UUIDS.DSA,
  'sk_docker': SKILL_UUIDS.DOCKER,
  'docker': SKILL_UUIDS.DOCKER,
  'sk_git': SKILL_UUIDS.GIT,
  'git': SKILL_UUIDS.GIT,
  'sk_ml': SKILL_UUIDS.ML,
  'machine learning': SKILL_UUIDS.ML,
  'ml': SKILL_UUIDS.ML,
};

export function resolveSkillId(idOrName: string): string {
  if (!idOrName) return SKILL_UUIDS.REACT;
  const key = idOrName.toLowerCase();
  return SKILL_ALIAS_MAP[key] || idOrName;
}

export const DEMO_SKILLS: Skill[] = [
  { id: SKILL_UUIDS.REACT, name: 'React', category: 'FRONTEND', description: 'Component-based UI library & hooks ecosystem' },
  { id: SKILL_UUIDS.JAVASCRIPT, name: 'JavaScript', category: 'FRONTEND', description: 'Modern ECMAScript, closures, asynchronous events' },
  { id: SKILL_UUIDS.TYPESCRIPT, name: 'TypeScript', category: 'FRONTEND', description: 'Strict type systems, generics, and compiler options' },
  { id: SKILL_UUIDS.PYTHON, name: 'Python', category: 'BACKEND', description: 'Data structures, FastAPI, automation, backend scripts' },
  { id: SKILL_UUIDS.NODEJS, name: 'Node.js', category: 'BACKEND', description: 'Event loop, Express, microservices, streaming APIs' },
  { id: SKILL_UUIDS.SQL, name: 'SQL', category: 'DATABASE', description: 'Relational schema design, indexes, joins, aggregations' },
  { id: SKILL_UUIDS.DSA, name: 'DSA', category: 'CORE_CS', description: 'Data structures, graphs, dynamic programming, trees' },
  { id: SKILL_UUIDS.DOCKER, name: 'Docker', category: 'DEVOPS', description: 'Containerization, multi-stage builds, orchestration' },
  { id: SKILL_UUIDS.GIT, name: 'Git', category: 'ENGINEERING', description: 'Version control, branch rebasing, commit integrity' },
  { id: SKILL_UUIDS.ML, name: 'Machine Learning', category: 'AI_ML', description: 'Model training, scikit-learn, evaluation metrics' },
];

export const DEMO_CANDIDATES: Profile[] = [
  {
    id: 'cand_samarth',
    email: 'samarth.mn@example.com',
    full_name: 'Samarth M N',
    role: 'JOB_SEEKER',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    bio: 'Performance-obsessed Frontend Engineer specializing in React, TypeScript, and high-throughput real-time dashboards.',
    phone: '+91 98451 22345',
    location: 'Mysuru, Karnataka',
    education: 'B.E. Computer Science, NIE Mysuru',
    experience_years: 3.5,
    availability: 'IMMEDIATELY',
    preferred_job_type: 'FULL_TIME',
    preferred_location: 'HYBRID',
    github_url: 'https://github.com/samarth-mn',
    linkedin_url: 'https://linkedin.com/in/samarth-mn',
    portfolio_url: 'https://samarthmn.dev',
    certifications: [
      { name: 'Meta Certified Frontend Developer', issuer: 'Meta', year: 2024 },
      { name: 'TypeScript Deep Dive Specialist', issuer: 'FrontendMasters', year: 2023 }
    ],
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-09-20T10:00:00Z',
  },
  {
    id: 'cand_priya',
    email: 'priya.sharma@example.com',
    full_name: 'Priya Sharma',
    role: 'JOB_SEEKER',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250',
    bio: 'Full-stack developer focused on Node.js microservices and resilient React applications.',
    phone: '+91 98765 43210',
    location: 'Bengaluru, Karnataka',
    education: 'M.Tech Software Engineering, PES University',
    experience_years: 4,
    availability: '15_DAYS',
    preferred_job_type: 'FULL_TIME',
    preferred_location: 'HYBRID',
    github_url: 'https://github.com/priyasharma-dev',
    linkedin_url: 'https://linkedin.com/in/priyasharma-dev',
    created_at: '2026-02-10T09:00:00Z',
    updated_at: '2026-09-18T11:00:00Z',
  },
  {
    id: 'cand_rahul',
    email: 'rahul.verma@example.com',
    full_name: 'Rahul Verma',
    role: 'JOB_SEEKER',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    bio: 'Backend & Systems Engineer building scalable Python / FastAPI distributed services and database optimization.',
    phone: '+91 91234 56789',
    location: 'Mysuru, Karnataka',
    education: 'B.Tech Information Science, SJCE Mysuru',
    experience_years: 2.5,
    availability: 'IMMEDIATELY',
    preferred_job_type: 'FULL_TIME',
    preferred_location: 'REMOTE',
    github_url: 'https://github.com/rahulv-dev',
    linkedin_url: 'https://linkedin.com/in/rahulv-dev',
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-09-22T14:00:00Z',
  },
  {
    id: 'cand_ananya',
    email: 'ananya.iyer@example.com',
    full_name: 'Ananya Iyer',
    role: 'JOB_SEEKER',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
    bio: 'Frontend Architect passionate about accessible UI components, animations, and TypeScript state systems.',
    phone: '+91 97654 32198',
    location: 'Bengaluru, Karnataka',
    education: 'B.E. Computer Science, BMS College',
    experience_years: 5,
    availability: '1_MONTH',
    preferred_job_type: 'FULL_TIME',
    preferred_location: 'HYBRID',
    github_url: 'https://github.com/ananya-iyer',
    linkedin_url: 'https://linkedin.com/in/ananya-iyer',
    created_at: '2026-01-20T12:00:00Z',
    updated_at: '2026-09-15T09:00:00Z',
  },
  {
    id: 'cand_vikram',
    email: 'vikram.patel@example.com',
    full_name: 'Vikram Patel',
    role: 'JOB_SEEKER',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    bio: 'Full Stack Engineer with strong foundations in React, Node, and DevOps container pipelines.',
    phone: '+91 94455 66778',
    location: 'Hyderabad, Telangana',
    education: 'B.Tech CSE, NIT Warangal',
    experience_years: 3,
    availability: 'IMMEDIATELY',
    preferred_job_type: 'FULL_TIME',
    preferred_location: 'REMOTE',
    github_url: 'https://github.com/vikrampatel-code',
    linkedin_url: 'https://linkedin.com/in/vikrampatel-code',
    created_at: '2026-04-05T14:00:00Z',
    updated_at: '2026-09-24T16:00:00Z',
  },
  {
    id: 'cand_neha',
    email: 'neha.gupta@example.com',
    full_name: 'Neha Gupta',
    role: 'JOB_SEEKER',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
    bio: 'Machine Learning & Python developer with focus on recommendation systems and data pipelines.',
    phone: '+91 93322 11445',
    location: 'Mysuru, Karnataka',
    education: 'M.S. Data Science, University of Mysore',
    experience_years: 2,
    availability: '15_DAYS',
    preferred_job_type: 'FULL_TIME',
    preferred_location: 'HYBRID',
    github_url: 'https://github.com/nehagupta-ai',
    linkedin_url: 'https://linkedin.com/in/nehagupta-ai',
    created_at: '2026-02-18T11:00:00Z',
    updated_at: '2026-09-21T17:00:00Z',
  },
  {
    id: 'cand_aditya',
    email: 'aditya.rao@example.com',
    full_name: 'Aditya Rao',
    role: 'JOB_SEEKER',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=250',
    bio: 'Core algorithms and backend software developer. Solved 600+ LeetCode problems.',
    phone: '+91 95566 77889',
    location: 'Bengaluru, Karnataka',
    education: 'B.E. Computer Science, RVCE Bengaluru',
    experience_years: 1.5,
    availability: 'IMMEDIATELY',
    preferred_job_type: 'FULL_TIME',
    preferred_location: 'ONSITE',
    github_url: 'https://github.com/adityarao-cs',
    linkedin_url: 'https://linkedin.com/in/adityarao-cs',
    created_at: '2026-05-12T08:00:00Z',
    updated_at: '2026-09-19T13:00:00Z',
  },
  {
    id: 'cand_sneha',
    email: 'sneha.kulkarni@example.com',
    full_name: 'Sneha Kulkarni',
    role: 'JOB_SEEKER',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    bio: 'Frontend Engineer focused on modern web platforms, CSS architecture, and high accessibility standards.',
    phone: '+91 92233 44556',
    location: 'Mysuru, Karnataka',
    education: 'B.E. Information Science, Vidyavardhaka College',
    experience_years: 3,
    availability: '15_DAYS',
    preferred_job_type: 'FULL_TIME',
    preferred_location: 'HYBRID',
    github_url: 'https://github.com/snehak-web',
    linkedin_url: 'https://linkedin.com/in/snehak-web',
    created_at: '2026-03-22T10:00:00Z',
    updated_at: '2026-09-23T15:00:00Z',
  }
];

export const RECRUITER_DEFAULT_ID = '5a9909df-0192-4a9e-b3d3-a8520a0a3462';
export const COMPANY_DEFAULT_ID = 'e1000000-0000-0000-0000-000000000001';

export const DEMO_RECRUITERS: Profile[] = [
  {
    id: RECRUITER_DEFAULT_ID,
    email: 'karthik@cloudscale.io',
    full_name: 'Karthik Somayaji',
    role: 'RECRUITER',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
    bio: 'Lead Technical Talent Partner at CloudScale Systems.',
    phone: '+91 98800 12345',
    location: 'Bengaluru / Mysuru',
    education: 'MBA, IIM Bangalore',
    experience_years: 8,
    availability: 'IMMEDIATELY',
    preferred_job_type: 'FULL_TIME',
    preferred_location: 'HYBRID',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-09-25T10:00:00Z',
  }
];

export const DEMO_COMPANIES: Company[] = [
  {
    id: 'e1000000-0000-0000-0000-000000000001',
    recruiter_id: RECRUITER_DEFAULT_ID,
    name: 'CloudScale Systems',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=150',
    description: 'Enterprise cloud infrastructure and real-time developer productivity tooling company serving Fortune 500 tech teams.',
    industry: 'Cloud Infrastructure & Developer Tools',
    location: 'Bengaluru / Mysuru, India',
    website: 'https://cloudscale.io',
    company_size: '51-200',
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'e1000000-0000-0000-0000-000000000002',
    recruiter_id: RECRUITER_DEFAULT_ID,
    name: 'NexaFintech',
    logo_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=150',
    description: 'Next-generation payment gateway and real-time fraud mitigation engine processing over 12M daily transactions.',
    industry: 'FinTech & Payments',
    location: 'Bengaluru, India',
    website: 'https://nexafintech.co',
    company_size: '201-500',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'e1000000-0000-0000-0000-000000000003',
    recruiter_id: RECRUITER_DEFAULT_ID,
    name: 'HyperEdge AI',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=150',
    description: 'Autonomous edge intelligence and lightweight neural networks for robotics and industrial IoT.',
    industry: 'Artificial Intelligence & Robotics',
    location: 'Mysuru, India',
    website: 'https://hyperedge.ai',
    company_size: '11-50',
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'e1000000-0000-0000-0000-000000000004',
    recruiter_id: RECRUITER_DEFAULT_ID,
    name: 'DevSphere India',
    logo_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=150',
    description: 'Modern software engineering lab building high-reliability platforms across healthcare, retail, and mobility.',
    industry: 'Product Engineering Services',
    location: 'Mysuru, India',
    website: 'https://devsphere.in',
    company_size: '51-200',
    created_at: '2026-02-15T00:00:00Z',
  }
];

export const DEMO_JOBS: Job[] = [
  {
    id: 'job_frontend_cloudscale',
    company_id: 'comp_cloudscale',
    recruiter_id: 'rec_karthik',
    company: DEMO_COMPANIES[0],
    title: 'Senior Frontend Developer (React / TypeScript)',
    description: 'We are seeking an exceptional Frontend Engineer to lead our telemetry dashboard team. You will craft high-performance interactive visualizations, collaborate on component architecture, and eliminate rendering bottlenecks.',
    employment_type: 'FULL_TIME',
    location: 'Mysuru, Karnataka',
    work_mode: 'HYBRID',
    min_experience: 3,
    max_experience: 6,
    min_salary: 1800000,
    max_salary: 2800000,
    salary_currency: 'INR',
    deadline: '2026-10-30T23:59:59Z',
    status: 'PUBLISHED',
    assessment_required: true,
    skills: [
      { id: 'js_1', job_id: 'job_frontend_cloudscale', skill_id: 'sk_react', skill: DEMO_SKILLS[0], weight: 40, is_required: true, min_acceptable_score: 75 },
      { id: 'js_2', job_id: 'job_frontend_cloudscale', skill_id: 'sk_js', skill: DEMO_SKILLS[1], weight: 25, is_required: true, min_acceptable_score: 70 },
      { id: 'js_3', job_id: 'job_frontend_cloudscale', skill_id: 'sk_ts', skill: DEMO_SKILLS[2], weight: 20, is_required: true, min_acceptable_score: 70 },
      { id: 'js_4', job_id: 'job_frontend_cloudscale', skill_id: 'sk_git', skill: DEMO_SKILLS[8], weight: 15, is_required: true, min_acceptable_score: 65 },
    ],
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'job_backend_nexa',
    company_id: 'comp_nexafintech',
    recruiter_id: 'rec_karthik',
    company: DEMO_COMPANIES[1],
    title: 'Backend Systems Engineer (Python / FastAPI)',
    description: 'Join our high-throughput transaction platform. Design ACID-compliant distributed workflows, integrate real-time fraud mitigation services, and optimize PostgreSQL query plans.',
    employment_type: 'FULL_TIME',
    location: 'Bengaluru, Karnataka',
    work_mode: 'REMOTE',
    min_experience: 2,
    max_experience: 5,
    min_salary: 1600000,
    max_salary: 2400000,
    salary_currency: 'INR',
    deadline: '2026-10-25T23:59:59Z',
    status: 'PUBLISHED',
    assessment_required: true,
    skills: [
      { id: 'js_5', job_id: 'job_backend_nexa', skill_id: 'sk_py', skill: DEMO_SKILLS[3], weight: 40, is_required: true, min_acceptable_score: 75 },
      { id: 'js_6', job_id: 'job_backend_nexa', skill_id: 'sk_sql', skill: DEMO_SKILLS[5], weight: 30, is_required: true, min_acceptable_score: 70 },
      { id: 'js_7', job_id: 'job_backend_nexa', skill_id: 'sk_dsa', skill: DEMO_SKILLS[6], weight: 20, is_required: true, min_acceptable_score: 65 },
      { id: 'js_8', job_id: 'job_backend_nexa', skill_id: 'sk_docker', skill: DEMO_SKILLS[7], weight: 10, is_required: false, min_acceptable_score: 60 },
    ],
    created_at: '2026-09-05T09:00:00Z',
  },
  {
    id: 'job_fullstack_devsphere',
    company_id: 'comp_devsphere',
    recruiter_id: 'rec_karthik',
    company: DEMO_COMPANIES[3],
    title: 'Full Stack Engineer (React + Node.js)',
    description: 'Lead end-to-end feature delivery from database schema creation to clean responsive client state. We value proven project delivery and clean architecture.',
    employment_type: 'FULL_TIME',
    location: 'Mysuru, Karnataka',
    work_mode: 'HYBRID',
    min_experience: 2,
    max_experience: 4,
    min_salary: 1400000,
    max_salary: 2000000,
    salary_currency: 'INR',
    deadline: '2026-11-05T23:59:59Z',
    status: 'PUBLISHED',
    assessment_required: true,
    skills: [
      { id: 'js_9', job_id: 'job_fullstack_devsphere', skill_id: 'sk_react', skill: DEMO_SKILLS[0], weight: 35, is_required: true, min_acceptable_score: 70 },
      { id: 'js_10', job_id: 'job_fullstack_devsphere', skill_id: 'sk_node', skill: DEMO_SKILLS[4], weight: 35, is_required: true, min_acceptable_score: 70 },
      { id: 'js_11', job_id: 'job_fullstack_devsphere', skill_id: 'sk_sql', skill: DEMO_SKILLS[5], weight: 20, is_required: true, min_acceptable_score: 60 },
      { id: 'js_12', job_id: 'job_fullstack_devsphere', skill_id: 'sk_git', skill: DEMO_SKILLS[8], weight: 10, is_required: false, min_acceptable_score: 60 },
    ],
    created_at: '2026-09-10T11:00:00Z',
  },
  {
    id: 'job_ai_hyperedge',
    company_id: 'comp_hyperedge',
    recruiter_id: 'rec_karthik',
    company: DEMO_COMPANIES[2],
    title: 'Edge AI & Python Systems Engineer',
    description: 'Develop optimized model deployment pipelines for low-power edge hardware. Implement custom model quantization and benchmarking harnesses.',
    employment_type: 'FULL_TIME',
    location: 'Mysuru, Karnataka',
    work_mode: 'ONSITE',
    min_experience: 2,
    max_experience: 5,
    min_salary: 1900000,
    max_salary: 2700000,
    salary_currency: 'INR',
    deadline: '2026-10-20T23:59:59Z',
    status: 'PUBLISHED',
    assessment_required: true,
    skills: [
      { id: 'js_13', job_id: 'job_ai_hyperedge', skill_id: 'sk_py', skill: DEMO_SKILLS[3], weight: 40, is_required: true, min_acceptable_score: 80 },
      { id: 'js_14', job_id: 'job_ai_hyperedge', skill_id: 'sk_ml', skill: DEMO_SKILLS[9], weight: 35, is_required: true, min_acceptable_score: 75 },
      { id: 'js_15', job_id: 'job_ai_hyperedge', skill_id: 'sk_dsa', skill: DEMO_SKILLS[6], weight: 25, is_required: true, min_acceptable_score: 70 },
    ],
    created_at: '2026-09-12T14:00:00Z',
  }
];

export const DEMO_PROFILE_SKILLS: Record<string, ProfileSkill[]> = {
  cand_samarth: [
    {
      id: 'ps_sam_1',
      profile_id: 'cand_samarth',
      skill_id: 'sk_react',
      skill: DEMO_SKILLS[0],
      self_declared_level: 'ADVANCED',
      assessed_score: 91,
      project_count: 4,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-15T12:00:00Z',
    },
    {
      id: 'ps_sam_2',
      profile_id: 'cand_samarth',
      skill_id: 'sk_js',
      skill: DEMO_SKILLS[1],
      self_declared_level: 'EXPERT',
      assessed_score: 88,
      project_count: 5,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-15T12:00:00Z',
    },
    {
      id: 'ps_sam_3',
      profile_id: 'cand_samarth',
      skill_id: 'sk_ts',
      skill: DEMO_SKILLS[2],
      self_declared_level: 'ADVANCED',
      assessed_score: 84,
      project_count: 3,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-18T16:00:00Z',
    },
    {
      id: 'ps_sam_4',
      profile_id: 'cand_samarth',
      skill_id: 'sk_sql',
      skill: DEMO_SKILLS[5],
      self_declared_level: 'INTERMEDIATE',
      assessed_score: 86,
      project_count: 2,
      verification_status: 'ASSESSMENT_BACKED',
      verified_at: '2026-09-19T10:00:00Z',
    },
    {
      id: 'ps_sam_5',
      profile_id: 'cand_samarth',
      skill_id: 'sk_dsa',
      skill: DEMO_SKILLS[6],
      self_declared_level: 'ADVANCED',
      assessed_score: 84,
      project_count: 1,
      verification_status: 'ASSESSMENT_BACKED',
      verified_at: '2026-09-12T14:00:00Z',
    },
    {
      id: 'ps_sam_6',
      profile_id: 'cand_samarth',
      skill_id: 'sk_git',
      skill: DEMO_SKILLS[8],
      self_declared_level: 'ADVANCED',
      assessed_score: 96,
      project_count: 5,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-14T11:00:00Z',
    },
  ],
  cand_priya: [
    {
      id: 'ps_priya_1',
      profile_id: 'cand_priya',
      skill_id: 'sk_react',
      skill: DEMO_SKILLS[0],
      self_declared_level: 'ADVANCED',
      assessed_score: 85,
      project_count: 3,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-10T14:00:00Z',
    },
    {
      id: 'ps_priya_2',
      profile_id: 'cand_priya',
      skill_id: 'sk_node',
      skill: DEMO_SKILLS[4],
      self_declared_level: 'ADVANCED',
      assessed_score: 89,
      project_count: 4,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-11T16:00:00Z',
    },
    {
      id: 'ps_priya_3',
      profile_id: 'cand_priya',
      skill_id: 'sk_sql',
      skill: DEMO_SKILLS[5],
      self_declared_level: 'INTERMEDIATE',
      assessed_score: 82,
      project_count: 3,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-12T10:00:00Z',
    },
    {
      id: 'ps_priya_4',
      profile_id: 'cand_priya',
      skill_id: 'sk_js',
      skill: DEMO_SKILLS[1],
      self_declared_level: 'ADVANCED',
      assessed_score: 87,
      project_count: 4,
      verification_status: 'ASSESSMENT_BACKED',
      verified_at: '2026-09-12T11:00:00Z',
    }
  ],
  cand_rahul: [
    {
      id: 'ps_rahul_1',
      profile_id: 'cand_rahul',
      skill_id: 'sk_py',
      skill: DEMO_SKILLS[3],
      self_declared_level: 'EXPERT',
      assessed_score: 93,
      project_count: 4,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-08T15:00:00Z',
    },
    {
      id: 'ps_rahul_2',
      profile_id: 'cand_rahul',
      skill_id: 'sk_sql',
      skill: DEMO_SKILLS[5],
      self_declared_level: 'ADVANCED',
      assessed_score: 90,
      project_count: 3,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-09T17:00:00Z',
    },
    {
      id: 'ps_rahul_3',
      profile_id: 'cand_rahul',
      skill_id: 'sk_dsa',
      skill: DEMO_SKILLS[6],
      self_declared_level: 'ADVANCED',
      assessed_score: 88,
      project_count: 2,
      verification_status: 'ASSESSMENT_BACKED',
      verified_at: '2026-09-14T09:00:00Z',
    },
  ],
  cand_ananya: [
    {
      id: 'ps_ananya_1',
      profile_id: 'cand_ananya',
      skill_id: 'sk_react',
      skill: DEMO_SKILLS[0],
      self_declared_level: 'EXPERT',
      assessed_score: 94,
      project_count: 5,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-08-30T10:00:00Z',
    },
    {
      id: 'ps_ananya_2',
      profile_id: 'cand_ananya',
      skill_id: 'sk_ts',
      skill: DEMO_SKILLS[2],
      self_declared_level: 'ADVANCED',
      assessed_score: 91,
      project_count: 4,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-09-01T12:00:00Z',
    },
    {
      id: 'ps_ananya_3',
      profile_id: 'cand_ananya',
      skill_id: 'sk_js',
      skill: DEMO_SKILLS[1],
      self_declared_level: 'EXPERT',
      assessed_score: 92,
      project_count: 5,
      verification_status: 'FULLY_VERIFIED',
      verified_at: '2026-08-28T14:00:00Z',
    },
  ],
};

export const DEMO_PROJECTS: Record<string, Project[]> = {
  cand_samarth: [
    {
      id: 'proj_sam_1',
      profile_id: 'cand_samarth',
      title: 'DevPulse — Real-Time WebSocket Telemetry Board',
      description: 'Ultra-low latency dev monitoring dashboard with canvas charting, virtualized event lists, and sub-16ms render loops.',
      github_url: 'https://github.com/samarth-mn/devpulse-telemetry',
      live_url: 'https://devpulse.preview.dev',
      candidate_role: 'Sole Architect & Lead Developer',
      team_size: 1,
      completion_date: '2026-07-20',
      verification_status: 'REPOSITORY_CONNECTED',
      skills: [DEMO_SKILLS[0], DEMO_SKILLS[2], DEMO_SKILLS[1], DEMO_SKILLS[8]],
    },
    {
      id: 'proj_sam_2',
      profile_id: 'cand_samarth',
      title: 'KubeLens — Interactive Kubernetes Topology Visualizer',
      description: 'Dynamic graph diagramming interface for microservice clusters with node latency heatmap inspection and drag-and-drop orchestration.',
      github_url: 'https://github.com/samarth-mn/kubelens-visualizer',
      live_url: 'https://kubelens.preview.dev',
      candidate_role: 'Frontend Lead',
      team_size: 3,
      completion_date: '2026-05-15',
      verification_status: 'EVIDENCE_REVIEWED',
      skills: [DEMO_SKILLS[0], DEMO_SKILLS[1], DEMO_SKILLS[8]],
    },
    {
      id: 'proj_sam_3',
      profile_id: 'cand_samarth',
      title: 'HyperSQL — Browser-Based Schema & Query Studio',
      description: 'Monaco-backed SQL workspace with interactive execution plans, indexing advice hints, and client-side SQLite WASM runner.',
      github_url: 'https://github.com/samarth-mn/hypersql-studio',
      live_url: 'https://hypersql.preview.dev',
      candidate_role: 'Full Stack Creator',
      team_size: 2,
      completion_date: '2026-02-10',
      verification_status: 'REPOSITORY_CONNECTED',
      skills: [DEMO_SKILLS[0], DEMO_SKILLS[2], DEMO_SKILLS[5]],
    },
    {
      id: 'proj_sam_4',
      profile_id: 'cand_samarth',
      title: 'AlgoBench — Algorithm Complexity Benchmark Suite',
      description: 'Visual benchmark tool charting runtime curves for sorting, tree balancing, and shortest path algorithms.',
      github_url: 'https://github.com/samarth-mn/algobench',
      candidate_role: 'Creator',
      team_size: 1,
      completion_date: '2025-11-28',
      verification_status: 'LINK_VERIFIED',
      skills: [DEMO_SKILLS[1], DEMO_SKILLS[6]],
    }
  ],
  cand_priya: [
    {
      id: 'proj_priya_1',
      profile_id: 'cand_priya',
      title: 'PayStream — High-Throughput Node Webhook Gateway',
      description: 'Idempotent webhook delivery engine with Redis-backed deduplication and exponential retry queues.',
      github_url: 'https://github.com/priyasharma-dev/paystream',
      candidate_role: 'Backend Architect',
      team_size: 2,
      completion_date: '2026-06-30',
      verification_status: 'REPOSITORY_CONNECTED',
      skills: [DEMO_SKILLS[4], DEMO_SKILLS[5], DEMO_SKILLS[1]],
    }
  ],
  cand_rahul: [
    {
      id: 'proj_rahul_1',
      profile_id: 'cand_rahul',
      title: 'FastStream — Async Event Router with FastAPI',
      description: 'Distributed event processing system with Kafka consumer workers and PostgreSQL partition management.',
      github_url: 'https://github.com/rahulv-dev/faststream',
      candidate_role: 'Lead Systems Developer',
      team_size: 2,
      completion_date: '2026-08-14',
      verification_status: 'REPOSITORY_CONNECTED',
      skills: [DEMO_SKILLS[3], DEMO_SKILLS[5], DEMO_SKILLS[7]],
    }
  ]
};

export const DEMO_ASSESSMENTS: Assessment[] = [
  {
    id: 'asmt_cloudscale_frontend',
    job_id: 'job_frontend_cloudscale',
    creator_id: 'rec_karthik',
    title: 'Senior Frontend Engineering Challenge',
    description: 'Evaluate practical skills in JavaScript concurrency, algorithmic state caching, and object graph manipulation.',
    duration_minutes: 45,
    total_points: 100,
    status: 'PUBLISHED',
    created_at: '2026-09-02T10:00:00Z',
    questions: [
      {
        id: 'q_fe_1',
        assessment_id: 'asmt_cloudscale_frontend',
        skill_id: 'sk_js',
        skill: DEMO_SKILLS[1],
        title: 'Sliding Window Rate-Limiting Cache',
        statement: `Implement an in-memory cache function \`solution(calls, windowMs, maxCalls)\` that processes a series of timestamped requests and determines which requests are ALLOWED and which are BLOCKED by rate limits.\n\nInput is an array of timestamps [10, 50, 100, 120, 300]. For each timestamp, if count of allowed calls in [timestamp - windowMs, timestamp] < maxCalls, mark as true (allowed), else false (blocked).`,
        constraints: `• calls is a strictly ascending array of integer timestamps (ms)\n• windowMs >= 1\n• maxCalls >= 1\n• Return boolean array of same length as calls`,
        examples: [
          {
            input: '[[10, 20, 30, 40], 50, 2]',
            output: '[true, true, false, false]',
            explanation: 'Calls at 10 and 20 are allowed. Call at 30 and 40 fall within 50ms window and exceed limit of 2.'
          }
        ],
        starter_code: {
          javascript: `function solution(calls, windowMs, maxCalls) {\n  const results = [];\n  const allowed = [];\n  \n  for (const t of calls) {\n    // Filter active timestamps in window\n    while (allowed.length > 0 && allowed[0] <= t - windowMs) {\n      allowed.shift();\n    }\n    \n    if (allowed.length < maxCalls) {\n      allowed.push(t);\n      results.push(true);\n    } else {\n      results.push(false);\n    }\n  }\n  \n  return results;\n}`,
          python: `def solution(calls, window_ms, max_calls):\n    results = []\n    allowed = []\n    for t in calls:\n        while allowed and allowed[0] <= t - window_ms:\n            allowed.pop(0)\n        if len(allowed) < max_calls:\n            allowed.append(t)\n            results.append(True)\n        else:\n            results.append(False)\n    return results`
        },
        test_cases: [
          {
            id: 'tc_fe1_1',
            input: '[[10, 20, 30, 40], 50, 2]',
            expected_output: '[true,true,false,false]',
            is_hidden: false,
            explanation: 'Standard burst window verification'
          },
          {
            id: 'tc_fe1_2',
            input: '[[100, 200, 300, 400], 50, 1]',
            expected_output: '[true,true,true,true]',
            is_hidden: false,
            explanation: 'Separated calls spaced beyond window'
          },
          {
            id: 'tc_fe1_3',
            input: '[[10, 11, 12, 13, 14, 15], 10, 3]',
            expected_output: '[true,true,true,false,false,false]',
            is_hidden: true,
            explanation: 'High frequency tight burst'
          }
        ],
        difficulty: 'MEDIUM',
        points: 50,
        time_limit_sec: 3,
        memory_limit_mb: 256,
        order_index: 1,
      },
      {
        id: 'q_fe_2',
        assessment_id: 'asmt_cloudscale_frontend',
        skill_id: 'sk_ts',
        skill: DEMO_SKILLS[2],
        title: 'Deep Object Delta & Change Tracker',
        statement: `Given two configuration objects \`baseObj\` and \`updatedObj\`, write \`solution(baseObj, updatedObj)\` that returns an object representing only the changed, added, or deleted keys.\n\nKeys present in baseObj but missing in updatedObj should have value '__DELETED__'. Keys identical in both should not appear in the delta.`,
        constraints: `• Objects contain primitive keys or nested flat dictionaries\n• Returns delta object`,
        examples: [
          {
            input: '{"theme": "dark", "fontSize": 14}, {"theme": "light", "fontSize": 14, "autoSave": true}',
            output: '{"theme": "light", "autoSave": true}',
            explanation: 'theme changed, autoSave added, fontSize remained unchanged.'
          }
        ],
        starter_code: {
          javascript: `function solution(baseObj, updatedObj) {\n  const delta = {};\n  // Check updated & added\n  for (const key of Object.keys(updatedObj)) {\n    if (baseObj[key] !== updatedObj[key]) {\n      delta[key] = updatedObj[key];\n    }\n  }\n  // Check deleted\n  for (const key of Object.keys(baseObj)) {\n    if (!(key in updatedObj)) {\n      delta[key] = '__DELETED__';\n    }\n  }\n  return delta;\n}`,
          python: `def solution(base_obj, updated_obj):\n    delta = {}\n    for k, v in updated_obj.items():\n        if base_obj.get(k) != v:\n            delta[k] = v\n    for k in base_obj:\n        if k not in updated_obj:\n            delta[k] = '__DELETED__'\n    return delta`
        },
        test_cases: [
          {
            id: 'tc_fe2_1',
            input: '{"theme": "dark", "fontSize": 14}, {"theme": "light", "fontSize": 14, "autoSave": true}',
            expected_output: '{"theme":"light","autoSave":true}',
            is_hidden: false,
            explanation: 'Basic property update and addition'
          },
          {
            id: 'tc_fe2_2',
            input: '{"a": 1, "b": 2}, {"a": 1}',
            expected_output: '{"b":"__DELETED__"}',
            is_hidden: true,
            explanation: 'Property deletion test'
          }
        ],
        difficulty: 'MEDIUM',
        points: 50,
        time_limit_sec: 3,
        memory_limit_mb: 256,
        order_index: 2,
      }
    ]
  }
];

export const DEMO_ATTEMPTS: AssessmentAttempt[] = [
  {
    id: 'att_samarth_1',
    assessment_id: 'asmt_cloudscale_frontend',
    assessment: DEMO_ASSESSMENTS[0],
    candidate_id: 'cand_samarth',
    candidate: DEMO_CANDIDATES[0],
    status: 'EVALUATED',
    started_at: '2026-09-15T11:00:00Z',
    submitted_at: '2026-09-15T11:38:00Z',
    camera_enabled: true,
    mic_enabled: true,
    fullscreen_confirmed: true,
    integrity_status: 'NORMAL',
    integrity_summary: {
      tab_switches: 0,
      fullscreen_exits: 0,
      copy_attempts: 1,
      paste_attempts: 0,
      camera_dropouts: 0,
      total_flags: 1,
      status: 'NORMAL',
    },
    technical_score: 91,
    score_breakdown: {
      correctness: 48,
      efficiency: 18,
      code_quality: 14,
      test_coverage: 10,
      time_performance: 5,
      total_score: 91,
    },
    submissions: [
      {
        id: 'sub_sam_1',
        attempt_id: 'att_samarth_1',
        question_id: 'q_fe_1',
        language: 'javascript',
        code: `function solution(calls, windowMs, maxCalls) {\n  const results = [];\n  const allowed = [];\n  for (const t of calls) {\n    while (allowed.length > 0 && allowed[0] <= t - windowMs) {\n      allowed.shift();\n    }\n    if (allowed.length < maxCalls) {\n      allowed.push(t);\n      results.push(true);\n    } else {\n      results.push(false);\n    }\n  }\n  return results;\n}`,
        tests_passed: 3,
        total_tests: 3,
        execution_time_ms: 18,
        memory_used_mb: 32.4,
        score: 50,
        test_results: [
          { test_id: 'tc_fe1_1', input: '...', expected_output: '...', actual_output: '...', passed: true, execution_time_ms: 6, is_hidden: false },
          { test_id: 'tc_fe1_2', input: '...', expected_output: '...', actual_output: '...', passed: true, execution_time_ms: 5, is_hidden: false },
          { test_id: 'tc_fe1_3', input: '...', expected_output: '...', actual_output: '...', passed: true, execution_time_ms: 7, is_hidden: true },
        ],
        submitted_at: '2026-09-15T11:20:00Z',
      },
      {
        id: 'sub_sam_2',
        attempt_id: 'att_samarth_1',
        question_id: 'q_fe_2',
        language: 'javascript',
        code: `function solution(baseObj, updatedObj) {\n  const delta = {};\n  for (const key of Object.keys(updatedObj)) {\n    if (baseObj[key] !== updatedObj[key]) {\n      delta[key] = updatedObj[key];\n    }\n  }\n  for (const key of Object.keys(baseObj)) {\n    if (!(key in updatedObj)) {\n      delta[key] = '__DELETED__';\n    }\n  }\n  return delta;\n}`,
        tests_passed: 2,
        total_tests: 2,
        execution_time_ms: 12,
        memory_used_mb: 31.8,
        score: 50,
        test_results: [
          { test_id: 'tc_fe2_1', input: '...', expected_output: '...', actual_output: '...', passed: true, execution_time_ms: 6, is_hidden: false },
          { test_id: 'tc_fe2_2', input: '...', expected_output: '...', actual_output: '...', passed: true, execution_time_ms: 6, is_hidden: true },
        ],
        submitted_at: '2026-09-15T11:37:00Z',
      }
    ],
    integrity_events: [
      {
        id: 'ie_1',
        attempt_id: 'att_samarth_1',
        event_type: 'COPY_ATTEMPT',
        severity: 'LOW',
        metadata: { textLength: 18 },
        timestamp: '2026-09-15T11:15:20Z',
      }
    ]
  }
];

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: 'app_samarth_cloudscale',
    job_id: 'job_frontend_cloudscale',
    candidate_id: 'cand_samarth',
    job: DEMO_JOBS[0],
    candidate: DEMO_CANDIDATES[0],
    status: 'ASSESSMENT_COMPLETED',
    match_score: 91,
    applied_at: '2026-09-14T09:30:00Z',
    updated_at: '2026-09-15T12:00:00Z',
  },
  {
    id: 'app_ananya_cloudscale',
    job_id: 'job_frontend_cloudscale',
    candidate_id: 'cand_ananya',
    job: DEMO_JOBS[0],
    candidate: DEMO_CANDIDATES[3],
    status: 'SHORTLISTED',
    match_score: 87,
    applied_at: '2026-09-14T11:15:00Z',
    updated_at: '2026-09-16T10:00:00Z',
  },
  {
    id: 'app_priya_cloudscale',
    job_id: 'job_frontend_cloudscale',
    candidate_id: 'cand_priya',
    job: DEMO_JOBS[0],
    candidate: DEMO_CANDIDATES[1],
    status: 'REVIEWING',
    match_score: 83,
    applied_at: '2026-09-15T14:20:00Z',
  },
  {
    id: 'app_rahul_nexa',
    job_id: 'job_backend_nexa',
    candidate_id: 'cand_rahul',
    job: DEMO_JOBS[1],
    candidate: DEMO_CANDIDATES[2],
    status: 'INTERVIEW',
    match_score: 94,
    applied_at: '2026-09-10T16:00:00Z',
  }
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    user_id: 'cand_samarth',
    title: 'High Compatibility Job Match (91%)',
    message: 'Senior Frontend Developer at CloudScale Systems matches 91% of your verified skills (React, JavaScript, TypeScript, Git).',
    type: 'MATCH',
    related_job_id: 'job_frontend_cloudscale',
    is_read: false,
    created_at: '2026-09-14T08:30:00Z',
  },
  {
    id: 'notif_2',
    user_id: 'cand_samarth',
    title: 'Assessment Evaluated — Technical Score: 91/100',
    message: 'Your CloudScale Systems Frontend Challenge has been evaluated with a 91/100 score. Verified Skill Passport updated.',
    type: 'ASSESSMENT_RESULT',
    related_application_id: 'app_samarth_cloudscale',
    is_read: false,
    created_at: '2026-09-15T12:05:00Z',
  },
  {
    id: 'notif_3',
    user_id: 'rec_karthik',
    title: 'Candidate Completed Assessment',
    message: 'Samarth M N scored 91/100 on the Senior Frontend Engineering Challenge with Normal integrity signals.',
    type: 'APPLICATION_UPDATE',
    related_application_id: 'app_samarth_cloudscale',
    is_read: false,
    created_at: '2026-09-15T12:05:00Z',
  }
];
